name: Build

on: [push, pull_request]

permissions:
    contents: read
    checks: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - name: Use Node.js 22.x
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  node-version: 22.x
            - name: Install dependencies
              run: npm ci
            - name: Build packages
              run: npm run build
            - name: Build documentation
              run: npm run build:docs
            - name: Tests
              uses: Forsakringskassan/vitest-config@09162c2996701e49faf17cd569ab3591610a8094 # v5.0.1

    cypress-ct:
        name: Cypress Component Tests
        runs-on: ubuntu-latest
        if: false
        steps:
            - name: Checkout
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
            - name: Use Node.js 22.x
              uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
              with:
                  node-version: 22.x
            - name: Install dependencies
              run: npm ci
            - name: Build (minimal)
              run: npm run build
            - name: Cypress Component Testing
              uses: cypress-io/github-action@c541a95ea92d9239347a2355f2e895cd4b3f8060 # v7.4.6
              with:
                  summary-title: "Component tests"
                  browser: chrome
                  component: true
                  quiet: true
            - uses: actions/upload-artifact@cf430e030ddbb5b0abf93d22962f4752f3646cd9 # v7
              if: always()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
                  if-no-files-found: ignore
